# In myexceptions/user_exceptions.py

class UserNotFoundException(Exception):
    """Exception raised when a user is not found."""
    pass
